"""subcategoria_id en productos ahora es nullable y en caso de eliminarse la subcategoria, se establece null en subcategoria_id

Revision ID: 097c827de764
Revises: ae1496fd9c79
Create Date: 2025-01-30 01:07:59.781986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '097c827de764'
down_revision: Union[str, None] = 'ae1496fd9c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'subcategoria_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('productos_ibfk_1', 'productos', type_='foreignkey')
    op.create_foreign_key(None, 'productos', 'subcategorias_productos', ['subcategoria_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.create_foreign_key('productos_ibfk_1', 'productos', 'subcategorias_productos', ['subcategoria_id'], ['id'])
    op.alter_column('productos', 'subcategoria_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
