"""creando relaciones entre websites y site_visits

Revision ID: 0d362f88bc59
Revises: fc69866f8b24
Create Date: 2025-05-29 14:22:02.907741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d362f88bc59'
down_revision: Union[str, None] = 'fc69866f8b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visits', sa.Column('site_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'site_visits', 'websites', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_visits', type_='foreignkey')
    op.drop_column('site_visits', 'site_id')
    # ### end Alembic commands ###
