"""quitando id de cotizaciones

Revision ID: 0db0851dc368
Revises: 5c9d4fabf7cf
Create Date: 2025-02-13 00:19:46.712091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0db0851dc368'
down_revision: Union[str, None] = '5c9d4fabf7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos_cotizados', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('ix_productos_cotizados_id', table_name='productos_cotizados')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_productos_cotizados_id', 'productos_cotizados', ['id'], unique=False)
    op.alter_column('productos_cotizados', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
