"""corrigiendo relacion almacen - sucursal - gerente

Revision ID: 251b34ec5de5
Revises: 62001ff3f02a
Create Date: 2025-01-28 01:38:18.793557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '251b34ec5de5'
down_revision: Union[str, None] = '62001ff3f02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'almacenes', 'empleados', ['encargado_id'], ['id'])
    op.create_foreign_key(None, 'almacenes', 'sucursales', ['sucursal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('almacenes', 'inventarios_id')
    op.drop_constraint('empleados_ibfk_3', 'empleados', type_='foreignkey')
    op.drop_constraint('empleados_ibfk_4', 'empleados', type_='foreignkey')
    op.drop_column('empleados', 'encargado_almacenes_id')
    op.drop_column('empleados', 'gerente_sucursal_id')
    op.create_foreign_key('fk_gerente', 'sucursales', 'empleados', ['gerente_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'sucursales', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sucursales', type_='foreignkey')
    op.drop_constraint('fk_gerente', 'sucursales', type_='foreignkey')
    op.add_column('empleados', sa.Column('gerente_sucursal_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('empleados', sa.Column('encargado_almacenes_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('empleados_ibfk_4', 'empleados', 'almacenes', ['encargado_almacenes_id'], ['id'])
    op.create_foreign_key('empleados_ibfk_3', 'empleados', 'sucursales', ['gerente_sucursal_id'], ['id'])
    op.add_column('almacenes', sa.Column('inventarios_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'almacenes', type_='foreignkey')
    op.drop_constraint(None, 'almacenes', type_='foreignkey')
    # ### end Alembic commands ###
