"""agregar unidad de medida para mostrar nombre en lista pero almacenar clave en db

Revision ID: 2e7c9f920ef3
Revises: d73197896e91
Create Date: 2025-04-06 14:17:48.465614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7c9f920ef3'
down_revision: Union[str, None] = 'd73197896e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('unidad_medida', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'unidad_medida')
    # ### end Alembic commands ###
