"""add retencion de ISR a RESICO en cotizaciones

Revision ID: 3296a3a07065
Revises: 11a715422c9f
Create Date: 2025-02-27 18:30:59.226610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3296a3a07065'
down_revision: Union[str, None] = '11a715422c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones', sa.Column('isr_ret', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotizaciones', 'isr_ret')
    # ### end Alembic commands ###
