"""quitando unidad de medida de producto

Revision ID: 453fad7be55b
Revises: 432dc9cb85f6
Create Date: 2025-04-06 13:45:48.359158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '453fad7be55b'
down_revision: Union[str, None] = '432dc9cb85f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'unidad_medida')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('unidad_medida', mysql.VARCHAR(length=3), nullable=False))
    # ### end Alembic commands ###
