"""eliminando campo id de producto cotizado

Revision ID: 51a1cd8347e6
Revises: 0db0851dc368
Create Date: 2025-02-13 00:23:29.330850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a1cd8347e6'
down_revision: Union[str, None] = '0db0851dc368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_productos_cotizados_id'), 'productos_cotizados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_cotizados_id'), table_name='productos_cotizados')
    # ### end Alembic commands ###
