"""relacion_especialistas_areas

Revision ID: 60f99c9c339b
Revises: 2fd3dfacfc8b
Create Date: 2026-07-28 23:13:38.442392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60f99c9c339b'
down_revision: Union[str, None] = '2fd3dfacfc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('cedula_profesional', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.Column('universidad_egreso', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id')
    )
    op.create_index(op.f('ix_especialistas_area_id'), 'especialistas', ['area_id'], unique=False)
    op.create_index(op.f('ix_especialistas_cedula_profesional'), 'especialistas', ['cedula_profesional'], unique=True)
    op.create_index(op.f('ix_especialistas_id'), 'especialistas', ['id'], unique=False)
    op.add_column('citas', sa.Column('especialista_id', sa.Integer(), nullable=False))
    op.alter_column('citas', 'motivo',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('ix_citas_fecha_fin', table_name='citas')
    op.drop_index('ix_citas_fecha_inicio', table_name='citas')
    op.create_index(op.f('ix_citas_id'), 'citas', ['id'], unique=False)
    op.drop_constraint('citas_ibfk_2', 'citas', type_='foreignkey')
    op.create_foreign_key(None, 'citas', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'citas', 'especialistas', ['especialista_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'citas', type_='foreignkey')
    op.drop_constraint(None, 'citas', type_='foreignkey')
    op.create_foreign_key('citas_ibfk_2', 'citas', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_citas_id'), table_name='citas')
    op.create_index('ix_citas_fecha_inicio', 'citas', ['fecha_inicio'], unique=False)
    op.create_index('ix_citas_fecha_fin', 'citas', ['fecha_fin'], unique=False)
    op.alter_column('citas', 'motivo',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_column('citas', 'especialista_id')
    op.drop_index(op.f('ix_especialistas_id'), table_name='especialistas')
    op.drop_index(op.f('ix_especialistas_cedula_profesional'), table_name='especialistas')
    op.drop_index(op.f('ix_especialistas_area_id'), table_name='especialistas')
    op.drop_table('especialistas')
    # ### end Alembic commands ###
