"""mas errores en relaciones

Revision ID: 62001ff3f02a
Revises: 90a6c167f8a8
Create Date: 2025-01-28 01:00:08.489063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62001ff3f02a'
down_revision: Union[str, None] = '90a6c167f8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('empleados_ibfk_6', 'empleados', type_='foreignkey')
    op.drop_column('empleados', 'usuario_id')
    op.add_column('sucursales', sa.Column('gerente_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sucursales', 'gerente_id')
    op.add_column('empleados', sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('empleados_ibfk_6', 'empleados', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###
