"""corrigiendo relaciones

Revision ID: 90a6c167f8a8
Revises: 2bbaa39728d0
Create Date: 2025-01-28 00:41:09.416588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a6c167f8a8'
down_revision: Union[str, None] = '2bbaa39728d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('almacenes', sa.Column('inventarios_id', sa.Integer(), nullable=True))
    op.add_column('areas', sa.Column('empleado_id', sa.Integer(), nullable=True))
    op.add_column('empleados', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'empleados', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empleados', type_='foreignkey')
    op.drop_column('empleados', 'usuario_id')
    op.drop_column('areas', 'empleado_id')
    op.drop_column('almacenes', 'inventarios_id')
    # ### end Alembic commands ###
