"""implementacion_inventarios

Revision ID: 91044f071158
Revises: 0d362f88bc59
Create Date: 2025-07-23 12:57:27.267204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91044f071158'
down_revision: Union[str, None] = '0d362f88bc59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=100), nullable=True),
    sa.Column('fecha_factura', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'TARJETA_CREDITO', 'TARJETA_DEBITO', 'CREDITO', name='metodopago'), nullable=True),
    sa.Column('costo_envio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('descuento_general', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('impuesto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('ENTRADA', 'SALIDA', 'TRANSFERENCIA', 'AJUSTE', name='tipomovimiento'), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COMPLETADO', 'CANCELADO', name='estadomovimiento'), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entradas_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_entrada', sa.Enum('COMPRA', 'DEVOLUCION_CLIENTE', 'TRANSFERENCIA_RECIBIDA', 'AJUSTE_POSITIVO', 'PRODUCCION', 'DONACION', name='tipoentrada'), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('numero_documento', sa.String(length=100), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_actual', sa.Integer(), nullable=False),
    sa.Column('costo_promedio', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_ultima_entrada', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_salida', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('stock_maximo', sa.Integer(), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('almacen_id', 'producto_id', name='uix_almacen_producto')
    )
    op.create_table('productos_comprados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_inventario_id', table_name='inventario')
    op.drop_table('inventario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventario',
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('almacen_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('existencias', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], name='inventario_ibfk_2'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='inventario_ibfk_1'),
    sa.PrimaryKeyConstraint('producto_id', 'almacen_id', 'id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_inventario_id', 'inventario', ['id'], unique=False)
    op.drop_table('productos_comprados')
    op.drop_table('inventarios')
    op.drop_table('entradas_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_table('proveedores')
    op.drop_table('entradas_compra')
    # ### end Alembic commands ###
