"""Posibles cambios

Revision ID: 9e1b4e8e9ab2
Revises: cc8eec884d2a
Create Date: 2025-02-18 16:52:48.099811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1b4e8e9ab2'
down_revision: Union[str, None] = 'cc8eec884d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('cotizaciones', sa.Column('iva', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('cotizaciones', sa.Column('descuento_general', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('cotizaciones', sa.Column('gastos_envio', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('cotizaciones', sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotizaciones', 'total')
    op.drop_column('cotizaciones', 'gastos_envio')
    op.drop_column('cotizaciones', 'descuento_general')
    op.drop_column('cotizaciones', 'iva')
    op.drop_column('cotizaciones', 'subtotal')
    # ### end Alembic commands ###
