"""creando tablas areas, categorias_productos, departamentos_productos, empresas, inventario, logos, productos_cotizados, producto, subcategoria_producto, sucursal sin relaciones

Revision ID: b0458b63ddd5
Revises: 943f15d305fd
Create Date: 2025-01-27 17:59:40.507656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0458b63ddd5'
down_revision: Union[str, None] = '943f15d305fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departamentos_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calle', sa.String(length=255), nullable=True),
    sa.Column('numero_exterior', sa.String(length=50), nullable=True),
    sa.Column('numero_interior', sa.String(length=50), nullable=True),
    sa.Column('colonia', sa.String(length=255), nullable=True),
    sa.Column('localidad', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('SAT_certificate', sa.String(length=255), nullable=True),
    sa.Column('SAT_stamp', sa.String(length=255), nullable=True),
    sa.Column('regimen_fiscal', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('existencias', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('producto_id', 'almacen_id', 'id')
    )
    op.create_index(op.f('ix_inventario_id'), 'inventario', ['id'], unique=False)
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_cotizados',
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cotizacion_id', 'producto_id', 'id')
    )
    op.create_index(op.f('ix_productos_cotizados_id'), 'productos_cotizados', ['id'], unique=False)
    op.create_table('subcategorias_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calle', sa.String(length=255), nullable=True),
    sa.Column('numero_exterior', sa.String(length=50), nullable=True),
    sa.Column('numero_interior', sa.String(length=50), nullable=True),
    sa.Column('colonia', sa.String(length=255), nullable=True),
    sa.Column('localidad', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_cotizacion_productos_id', table_name='cotizacion_productos')
    op.drop_table('cotizacion_productos')
    op.add_column('almacenes', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('almacenes', sa.Column('calle', sa.String(length=255), nullable=True))
    op.add_column('almacenes', sa.Column('numero_exterior', sa.String(length=50), nullable=True))
    op.add_column('almacenes', sa.Column('numero_interior', sa.String(length=50), nullable=True))
    op.add_column('almacenes', sa.Column('colonia', sa.String(length=255), nullable=True))
    op.add_column('almacenes', sa.Column('localidad', sa.String(length=255), nullable=True))
    op.add_column('almacenes', sa.Column('municipio', sa.String(length=255), nullable=True))
    op.add_column('almacenes', sa.Column('estado', sa.String(length=100), nullable=True))
    op.add_column('almacenes', sa.Column('codigo_postal', sa.String(length=5), nullable=True))
    op.add_column('almacenes', sa.Column('type', sa.String(length=100), nullable=True))
    op.add_column('almacenes', sa.Column('sucursal_id', sa.Integer(), nullable=False))
    op.drop_constraint('almacenes_ibfk_1', 'almacenes', type_='foreignkey')
    op.drop_column('almacenes', 'tipo')
    op.drop_column('almacenes', 'nombre')
    op.add_column('clientes', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.add_column('clientes', sa.Column('nombre_fiscal', sa.String(length=255), nullable=False))
    op.add_column('clientes', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('clientes', sa.Column('land_line', sa.String(length=15), nullable=True))
    op.add_column('clientes', sa.Column('phone_number', sa.String(length=15), nullable=True))
    op.add_column('clientes', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('clientes', 'regimen_fiscal',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('NOSE', name='regimenfiscal'),
               nullable=False)
    op.drop_index('ix_clientes_id', table_name='clientes')
    op.drop_index('rfc', table_name='clientes')
    op.drop_column('clientes', 'emails')
    op.drop_column('clientes', 'nombre_contacto')
    op.drop_column('clientes', 'telefonos_celulares')
    op.drop_column('clientes', 'facturar_ventas')
    op.drop_column('clientes', 'monto_credito')
    op.drop_column('clientes', 'dias_credito')
    op.drop_column('clientes', 'razon_social')
    op.drop_column('clientes', 'telefonos_fijos')
    op.add_column('cotizaciones', sa.Column('logo_id', sa.Integer(), nullable=True))
    op.drop_constraint('cotizaciones_ibfk_2', 'cotizaciones', type_='foreignkey')
    op.drop_constraint('cotizaciones_ibfk_1', 'cotizaciones', type_='foreignkey')
    op.drop_column('cotizaciones', 'descuento_general')
    op.drop_column('cotizaciones', 'subtotal')
    op.drop_column('cotizaciones', 'fecha_vencimiento')
    op.drop_column('cotizaciones', 'gastos_envio')
    op.drop_column('cotizaciones', 'condiciones_venta')
    op.drop_column('cotizaciones', 'iva')
    op.drop_column('cotizaciones', 'fecha_emision')
    op.drop_column('cotizaciones', 'total')
    op.drop_column('cotizaciones', 'observaciones')
    op.create_foreign_key('fk_empleado_almacen', 'empleados', 'almacenes', ['almacen_id'], ['id'], use_alter=True)
    op.add_column('productos', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('productos', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('productos', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('productos', sa.Column('SAT_code', sa.String(length=50), nullable=True))
    op.add_column('productos', sa.Column('warranty', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('productos', sa.Column('images', sa.String(length=255), nullable=True))
    op.add_column('productos', sa.Column('sell_price', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('rent_price', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('subcategoria_id', sa.Integer(), nullable=False))
    op.drop_constraint('productos_ibfk_1', 'productos', type_='foreignkey')
    op.drop_column('productos', 'concepto_sat')
    op.drop_column('productos', 'unidad_venta')
    op.drop_column('productos', 'descripcion')
    op.drop_column('productos', 'marca')
    op.drop_column('productos', 'clave_sat')
    op.drop_column('productos', 'modelo')
    op.drop_column('productos', 'almacen_id')
    op.drop_column('productos', 'precio_venta')
    op.drop_column('productos', 'unidad_compra')
    op.drop_column('productos', 'color')
    op.drop_column('productos', 'precio_renta')
    op.drop_column('productos', 'peso')
    op.drop_column('productos', 'um_sat')
    op.drop_column('productos', 'dimensiones')
    op.drop_column('productos', 'factor')
    op.drop_column('productos', 'dias_garantia')
    op.drop_column('productos', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('productos', sa.Column('dias_garantia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('factor', mysql.FLOAT(), nullable=True))
    op.add_column('productos', sa.Column('dimensiones', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('productos', sa.Column('um_sat', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('productos', sa.Column('peso', mysql.FLOAT(), nullable=True))
    op.add_column('productos', sa.Column('precio_renta', mysql.FLOAT(), nullable=True))
    op.add_column('productos', sa.Column('color', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('productos', sa.Column('unidad_compra', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('productos', sa.Column('precio_venta', mysql.FLOAT(), nullable=False))
    op.add_column('productos', sa.Column('almacen_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('modelo', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('productos', sa.Column('clave_sat', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('productos', sa.Column('marca', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('productos', sa.Column('descripcion', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('productos', sa.Column('unidad_venta', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('productos', sa.Column('concepto_sat', mysql.VARCHAR(length=255), nullable=True))
    op.create_foreign_key('productos_ibfk_1', 'productos', 'almacenes', ['almacen_id'], ['id'])
    op.drop_column('productos', 'subcategoria_id')
    op.drop_column('productos', 'rent_price')
    op.drop_column('productos', 'sell_price')
    op.drop_column('productos', 'images')
    op.drop_column('productos', 'description')
    op.drop_column('productos', 'warranty')
    op.drop_column('productos', 'SAT_code')
    op.drop_column('productos', 'brand')
    op.drop_column('productos', 'model')
    op.drop_column('productos', 'name')
    op.drop_constraint('fk_empleado_almacen', 'empleados', type_='foreignkey')
    op.add_column('cotizaciones', sa.Column('observaciones', mysql.TEXT(), nullable=True))
    op.add_column('cotizaciones', sa.Column('total', mysql.FLOAT(), nullable=False))
    op.add_column('cotizaciones', sa.Column('fecha_emision', mysql.DATETIME(), nullable=False))
    op.add_column('cotizaciones', sa.Column('iva', mysql.FLOAT(), nullable=False))
    op.add_column('cotizaciones', sa.Column('condiciones_venta', mysql.TEXT(), nullable=True))
    op.add_column('cotizaciones', sa.Column('gastos_envio', mysql.FLOAT(), nullable=False))
    op.add_column('cotizaciones', sa.Column('fecha_vencimiento', sa.DATE(), nullable=False))
    op.add_column('cotizaciones', sa.Column('subtotal', mysql.FLOAT(), nullable=False))
    op.add_column('cotizaciones', sa.Column('descuento_general', mysql.FLOAT(), nullable=False))
    op.create_foreign_key('cotizaciones_ibfk_1', 'cotizaciones', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key('cotizaciones_ibfk_2', 'cotizaciones', 'emisores', ['emisor_id'], ['id'])
    op.drop_column('cotizaciones', 'logo_id')
    op.add_column('clientes', sa.Column('telefonos_fijos', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('clientes', sa.Column('razon_social', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('clientes', sa.Column('dias_credito', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('monto_credito', mysql.FLOAT(), nullable=True))
    op.add_column('clientes', sa.Column('facturar_ventas', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('telefonos_celulares', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('clientes', sa.Column('nombre_contacto', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('clientes', sa.Column('emails', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.create_index('rfc', 'clientes', ['rfc'], unique=True)
    op.create_index('ix_clientes_id', 'clientes', ['id'], unique=False)
    op.alter_column('clientes', 'regimen_fiscal',
               existing_type=sa.Enum('NOSE', name='regimenfiscal'),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('clientes', 'email')
    op.drop_column('clientes', 'phone_number')
    op.drop_column('clientes', 'land_line')
    op.drop_column('clientes', 'contact_name')
    op.drop_column('clientes', 'nombre_fiscal')
    op.drop_column('clientes', 'empresa_id')
    op.add_column('almacenes', sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('almacenes', sa.Column('tipo', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key('almacenes_ibfk_1', 'almacenes', 'empleados', ['encargado_id'], ['id'])
    op.drop_column('almacenes', 'sucursal_id')
    op.drop_column('almacenes', 'type')
    op.drop_column('almacenes', 'codigo_postal')
    op.drop_column('almacenes', 'estado')
    op.drop_column('almacenes', 'municipio')
    op.drop_column('almacenes', 'localidad')
    op.drop_column('almacenes', 'colonia')
    op.drop_column('almacenes', 'numero_interior')
    op.drop_column('almacenes', 'numero_exterior')
    op.drop_column('almacenes', 'calle')
    op.drop_column('almacenes', 'name')
    op.create_table('cotizacion_productos',
    sa.Column('cotizacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.FLOAT(), nullable=False),
    sa.Column('precio_unitario', mysql.FLOAT(), nullable=False),
    sa.Column('descuento', mysql.FLOAT(), nullable=False),
    sa.Column('importe', mysql.FLOAT(), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], name='cotizacion_productos_ibfk_1'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='cotizacion_productos_ibfk_2'),
    sa.PrimaryKeyConstraint('cotizacion_id', 'producto_id', 'id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_cotizacion_productos_id', 'cotizacion_productos', ['id'], unique=False)
    op.drop_table('sucursales')
    op.drop_table('subcategorias_productos')
    op.drop_index(op.f('ix_productos_cotizados_id'), table_name='productos_cotizados')
    op.drop_table('productos_cotizados')
    op.drop_table('logos')
    op.drop_index(op.f('ix_inventario_id'), table_name='inventario')
    op.drop_table('inventario')
    op.drop_table('empresas')
    op.drop_table('departamentos_productos')
    op.drop_table('categorias_productos')
    op.drop_table('areas')
    # ### end Alembic commands ###
