"""regimen fiscal cambiado temporalmente a string

Revision ID: b61832b124d3
Revises: bf3a36d3b55a
Create Date: 2025-02-10 16:03:21.785569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b61832b124d3'
down_revision: Union[str, None] = 'bf3a36d3b55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'regimen_fiscal',
               existing_type=mysql.ENUM('NOSE'),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'regimen_fiscal',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('NOSE'),
               existing_nullable=True)
    # ### end Alembic commands ###
