"""remover unidad de medida para mostrar nombre en lista pero almacenar clave en db

Revision ID: d73197896e91
Revises: e56a7d316c06
Create Date: 2025-04-06 14:16:15.633087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd73197896e91'
down_revision: Union[str, None] = 'e56a7d316c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'unidad_medida')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('unidad_medida', mysql.VARCHAR(length=4), nullable=False))
    # ### end Alembic commands ###
