"""agregando campos a proveedores

Revision ID: f650b0a4f58e
Revises: 7f075689b75e
Create Date: 2025-07-30 12:50:14.373827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f650b0a4f58e'
down_revision: Union[str, None] = '7f075689b75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedores', sa.Column('calle', sa.String(length=255), nullable=True))
    op.add_column('proveedores', sa.Column('numero_exterior', sa.String(length=50), nullable=True))
    op.add_column('proveedores', sa.Column('numero_interior', sa.String(length=50), nullable=True))
    op.add_column('proveedores', sa.Column('colonia', sa.String(length=255), nullable=True))
    op.add_column('proveedores', sa.Column('localidad', sa.String(length=255), nullable=True))
    op.add_column('proveedores', sa.Column('municipio', sa.String(length=255), nullable=True))
    op.add_column('proveedores', sa.Column('estado', sa.String(length=100), nullable=True))
    op.add_column('proveedores', sa.Column('codigo_postal', sa.String(length=5), nullable=True))
    op.add_column('proveedores', sa.Column('observaciones', sa.String(length=200), nullable=True))
    op.add_column('proveedores', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.alter_column('proveedores', 'telefono',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('proveedores', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'proveedores', 'empresas', ['empresa_id'], ['id'])
    op.drop_column('proveedores', 'direccion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedores', sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'proveedores', type_='foreignkey')
    op.alter_column('proveedores', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('proveedores', 'telefono',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('proveedores', 'empresa_id')
    op.drop_column('proveedores', 'observaciones')
    op.drop_column('proveedores', 'codigo_postal')
    op.drop_column('proveedores', 'estado')
    op.drop_column('proveedores', 'municipio')
    op.drop_column('proveedores', 'localidad')
    op.drop_column('proveedores', 'colonia')
    op.drop_column('proveedores', 'numero_interior')
    op.drop_column('proveedores', 'numero_exterior')
    op.drop_column('proveedores', 'calle')
    # ### end Alembic commands ###
