"""en emisores cambiado regimen fiscal a enums

Revision ID: fb6b6be89e75
Revises: dd8266386329
Create Date: 2025-02-10 17:03:07.433501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb6b6be89e75'
down_revision: Union[str, None] = 'dd8266386329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emisores', 'tipo_persona',
               existing_type=mysql.ENUM('FISICA', 'MORAL'),
               nullable=True)
    op.alter_column('emisores', 'regimen_fiscal',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('605 - Sueldos y Salarios e Ingresos Asimilados a Salarios', '606 - Arrendamiento', '607 - Régimen de Enajenación o Adquisición de Bienes', '608 - Demás ingresos', '609 - Consolidación', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México', '611 - Personas Físicas con Actividades Empresariales y Profesionales', '612 - Personas Físicas con Actividades Empresariales y Profesionales', '614 - Ingresos por intereses', '615 - Régimen de ingresos por obtención de premios', '616 - Sin obligaciones fiscales', '621 - Incorporación fiscal', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas', '626 - Régimen Simplificado de Confianza', '630 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales', '601 - General de Ley Personas Morales', '603 - Personas Morales con Fines no Lucrativos', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos', '623 - Opcional para Grupos de Sociedades', '624 - Coordinados', '628 - Hidrocarburos', '629 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales', name='regimenfiscal'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emisores', 'regimen_fiscal',
               existing_type=sa.Enum('605 - Sueldos y Salarios e Ingresos Asimilados a Salarios', '606 - Arrendamiento', '607 - Régimen de Enajenación o Adquisición de Bienes', '608 - Demás ingresos', '609 - Consolidación', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México', '611 - Personas Físicas con Actividades Empresariales y Profesionales', '612 - Personas Físicas con Actividades Empresariales y Profesionales', '614 - Ingresos por intereses', '615 - Régimen de ingresos por obtención de premios', '616 - Sin obligaciones fiscales', '621 - Incorporación fiscal', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas', '626 - Régimen Simplificado de Confianza', '630 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales', '601 - General de Ley Personas Morales', '603 - Personas Morales con Fines no Lucrativos', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos', '623 - Opcional para Grupos de Sociedades', '624 - Coordinados', '628 - Hidrocarburos', '629 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales', name='regimenfiscal'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('emisores', 'tipo_persona',
               existing_type=mysql.ENUM('FISICA', 'MORAL'),
               nullable=False)
    # ### end Alembic commands ###
