"""agregando campos de direccion mas especificos a empleado

Revision ID: fcacf44dd658
Revises: 1a90891633c2
Create Date: 2025-01-28 17:43:54.091294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fcacf44dd658'
down_revision: Union[str, None] = '1a90891633c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('calle', sa.String(length=255), nullable=True))
    op.add_column('empleados', sa.Column('numero_exterior', sa.String(length=50), nullable=True))
    op.add_column('empleados', sa.Column('numero_interior', sa.String(length=50), nullable=True))
    op.add_column('empleados', sa.Column('colonia', sa.String(length=255), nullable=True))
    op.add_column('empleados', sa.Column('localidad', sa.String(length=255), nullable=True))
    op.add_column('empleados', sa.Column('municipio', sa.String(length=255), nullable=True))
    op.add_column('empleados', sa.Column('estado', sa.String(length=100), nullable=True))
    op.add_column('empleados', sa.Column('codigo_postal', sa.String(length=5), nullable=True))
    op.drop_column('empleados', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('address', mysql.TEXT(), nullable=True))
    op.drop_column('empleados', 'codigo_postal')
    op.drop_column('empleados', 'estado')
    op.drop_column('empleados', 'municipio')
    op.drop_column('empleados', 'localidad')
    op.drop_column('empleados', 'colonia')
    op.drop_column('empleados', 'numero_interior')
    op.drop_column('empleados', 'numero_exterior')
    op.drop_column('empleados', 'calle')
    # ### end Alembic commands ###
