services:
  mariadb:
    image: mariadb:11.7
    container_name: tadimex-mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d   
    ports:
      - "3307:3306"
    networks:
      - tadimex-network
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h 127.0.0.1 -u${MARIADB_USER} -p${MARIADB_PASSWORD} -D ${MARIADB_DATABASE} -e 'SELECT 1' >/dev/null 2>&1 || exit 1"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 10
 
  backend:
    build: ./tadimex-backend
    image: tadimex-backend:latest
    container_name: tadimex-backend
    restart: always
    env_file:
      - .env
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - CORS_ORIGINS=["http://localhost", "http://localhost:80"]
    volumes:
      - backend_data:/app/data
      - backend_static:/app/static
    ports:
      - "8000:8000" 
    networks:
      - tadimex-network
    depends_on:
      mariadb:
        condition: service_healthy

  frontend:
    build: ./tadimex-frontend
    image: tadimex-frontend:latest
    container_name: tadimex-frontend
    restart: always
    environment:
      - VITE_API_SERVER=http://tadimex-backend:8000
    volumes: 
      - frontend_build:/usr/share/nginx/html
    networks:
      - tadimex-network
    depends_on:
      - backend
 
  nginx:
    image: nginx:latest
    container_name: tadimex-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${FRONTEND_PATH}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - backend_static:/usr/share/nginx/static:ro
      - frontend_build:/usr/share/nginx/html:ro
    networks:
      - tadimex-network
    depends_on:
      - frontend
      - backend

networks:
  tadimex-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  backend_data:
    driver: local
  backend_static:
    driver: local
  frontend_build:
    driver: local
