name: clinica-nochistlan
services:
  mariadb:
    image: mariadb:11.7
    container_name: clinica-mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    networks:
      - clinica-network
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h 127.0.0.1 -u${MARIADB_USER} -p${MARIADB_PASSWORD} -D ${MARIADB_DATABASE} -e 'SELECT 1' >/dev/null 2>&1 || exit 1"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./clinica-backend
    image: clinica-backend:latest
    container_name: clinica-backend
    restart: always
    env_file:
      - .env
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - BACKEND_CORS_ORIGINS=["http://localhost:8082", "http://localhost:8001"]
    volumes:
      - backend_data:/app/data
      - backend_static:/app/static
    ports:
      - "8001:8000"
    networks:
      - clinica-network
    depends_on:
      mariadb:
        condition: service_healthy

  frontend:
    build:
      context: ./clinica-frontend
      args:
        - VITE_API_SERVER=${VITE_API_SERVER}
    image: clinica-frontend:latest
    container_name: clinica-frontend
    restart: always
    ports:
      - "8082:80"
    volumes:
      - backend_static:/usr/share/nginx/static:ro
    networks:
      - clinica-network
    depends_on:
      - backend

networks:
  clinica-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  backend_data:
    driver: local
  backend_static:
    driver: local