"""add observaciones to clientes

Revision ID: 11a715422c9f
Revises: 497b1c9e21dc
Create Date: 2025-02-27 15:44:40.468797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a715422c9f'
down_revision: Union[str, None] = '497b1c9e21dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('observaciones', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'observaciones')
    # ### end Alembic commands ###
