"""agregando nombre a foreign kede subcategoria_id y nullable true a subcategoria

Revision ID: 1c056c561453
Revises: 097c827de764
Create Date: 2025-01-30 01:21:55.481276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c056c561453'
down_revision: Union[str, None] = '097c827de764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('productos_ibfk_1', 'productos', type_='foreignkey')
    op.create_foreign_key('fk_productos_subcategoria_id', 'productos', 'subcategorias_productos', ['subcategoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_productos_subcategoria_id', 'productos', type_='foreignkey')
    op.create_foreign_key('productos_ibfk_1', 'productos', 'subcategorias_productos', ['subcategoria_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
