"""creando las relaciones para todas las tablas

Revision ID: 2bbaa39728d0
Revises: b0458b63ddd5
Create Date: 2025-01-27 23:48:39.143691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2bbaa39728d0'
down_revision: Union[str, None] = 'b0458b63ddd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('almacenes', 'type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('PRINCIPAL', 'SECUNDARIO', 'GARAGE', name='tipoalmacen'),
               existing_nullable=True)
    op.add_column('empleados', sa.Column('area_id', sa.Integer(), nullable=True))
    op.add_column('empleados', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.add_column('empleados', sa.Column('gerente_sucursal_id', sa.Integer(), nullable=True))
    op.add_column('empleados', sa.Column('encargado_almacenes_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_empleado_almacen', 'empleados', type_='foreignkey')
    op.create_foreign_key(None, 'empleados', 'areas', ['area_id'], ['id'])
    op.create_foreign_key(None, 'empleados', 'sucursales', ['gerente_sucursal_id'], ['id'])
    op.create_foreign_key(None, 'empleados', 'almacenes', ['encargado_almacenes_id'], ['id'])
    op.create_foreign_key(None, 'empleados', 'sucursales', ['sucursal_id'], ['id'])
    op.drop_column('empleados', 'almacen_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('almacen_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'empleados', type_='foreignkey')
    op.drop_constraint(None, 'empleados', type_='foreignkey')
    op.drop_constraint(None, 'empleados', type_='foreignkey')
    op.drop_constraint(None, 'empleados', type_='foreignkey')
    op.create_foreign_key('fk_empleado_almacen', 'empleados', 'almacenes', ['almacen_id'], ['id'])
    op.drop_column('empleados', 'encargado_almacenes_id')
    op.drop_column('empleados', 'gerente_sucursal_id')
    op.drop_column('empleados', 'sucursal_id')
    op.drop_column('empleados', 'area_id')
    op.alter_column('almacenes', 'type',
               existing_type=sa.Enum('PRINCIPAL', 'SECUNDARIO', 'GARAGE', name='tipoalmacen'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
