"""creando tabla conceptos sat

Revision ID: 30b5bb2eb86b
Revises: 43c8f92d1268
Create Date: 2025-03-20 12:55:59.598881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b5bb2eb86b'
down_revision: Union[str, None] = '43c8f92d1268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conceptos_sat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.String(length=10), nullable=False),
    sa.Column('segmento', sa.String(length=2), nullable=True),
    sa.Column('familia', sa.String(length=2), nullable=True),
    sa.Column('clase', sa.String(length=2), nullable=True),
    sa.Column('mercancia', sa.String(length=2), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conceptos_sat')
    # ### end Alembic commands ###
