"""sell price en productos cambia a decimal

Revision ID: 43c8f92d1268
Revises: c281846f9785
Create Date: 2025-03-14 15:31:08.753888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43c8f92d1268'
down_revision: Union[str, None] = 'c281846f9785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'sell_price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'sell_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
