"""add fecha_vencimiento, folio tabla cotizaciones

Revision ID: 497b1c9e21dc
Revises: 9e1b4e8e9ab2
Create Date: 2025-02-20 12:06:07.115310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497b1c9e21dc'
down_revision: Union[str, None] = '9e1b4e8e9ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones', sa.Column('folio', sa.String(length=50), nullable=True))
    op.add_column('cotizaciones', sa.Column('fecha_vencimiento', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'cotizaciones', ['folio'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cotizaciones', type_='unique')
    op.drop_column('cotizaciones', 'fecha_vencimiento')
    op.drop_column('cotizaciones', 'folio')
    # ### end Alembic commands ###
