"""cambiando tipo de dato de campo images en productos de string a json para admitir lista de urls de imagenes

Revision ID: 518ded7fbf43
Revises: 1c056c561453
Create Date: 2025-02-07 11:20:45.357914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '518ded7fbf43'
down_revision: Union[str, None] = '1c056c561453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'images',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'images',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
