"""agregando campos en cotizacion y productos cotizados

Revision ID: 5c9d4fabf7cf
Revises: fb6b6be89e75
Create Date: 2025-02-12 22:51:28.624113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9d4fabf7cf'
down_revision: Union[str, None] = 'fb6b6be89e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones', sa.Column('observaciones', sa.String(length=255), nullable=True))
    op.add_column('cotizaciones', sa.Column('condiciones_venta', sa.String(length=255), nullable=True))
    op.add_column('productos_cotizados', sa.Column('cantidad', sa.Integer(), nullable=False))
    op.add_column('productos_cotizados', sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos_cotizados', 'descuento')
    op.drop_column('productos_cotizados', 'cantidad')
    op.drop_column('cotizaciones', 'condiciones_venta')
    op.drop_column('cotizaciones', 'observaciones')
    # ### end Alembic commands ###
