"""empleado - sucursal correccion

Revision ID: 6a2dc3c6c705
Revises: ca39ffd9dfdb
Create Date: 2025-01-28 02:45:53.643496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2dc3c6c705'
down_revision: Union[str, None] = 'ca39ffd9dfdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
