"""migracion prueba

Revision ID: 74cbe3275062
Revises: 7ef4227fa932
Create Date: 2025-02-18 16:28:22.788376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '74cbe3275062'
down_revision: Union[str, None] = '7ef4227fa932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos_cotizados')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_cotizados',
    sa.Column('cotizacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('descuento', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], name='productos_cotizados_ibfk_1'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='productos_cotizados_ibfk_2'),
    sa.PrimaryKeyConstraint('cotizacion_id', 'producto_id', 'id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
