"""agregando campo id y llave compuesta

Revision ID: 7ef4227fa932
Revises: 51a1cd8347e6
Create Date: 2025-02-13 00:30:16.888713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef4227fa932'
down_revision: Union[str, None] = '51a1cd8347e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productos_cotizados_id', table_name='productos_cotizados')
    op.create_unique_constraint('uq_cotizacion_producto', 'productos_cotizados', ['cotizacion_id', 'producto_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cotizacion_producto', 'productos_cotizados', type_='unique')
    op.create_index('ix_productos_cotizados_id', 'productos_cotizados', ['id'], unique=False)
    # ### end Alembic commands ###
