"""agregando campos de precio original a la tabla de producto comprado

Revision ID: 7f075689b75e
Revises: 8bc1ceabbebb
Create Date: 2025-07-28 13:04:39.220893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f075689b75e'
down_revision: Union[str, None] = '8bc1ceabbebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos_comprados', sa.Column('precio_unitario_original', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('productos_comprados', sa.Column('incluye_iva_original', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos_comprados', 'incluye_iva_original')
    op.drop_column('productos_comprados', 'precio_unitario_original')
    # ### end Alembic commands ###
