"""agrando estado cliente a clientes

Revision ID: 85a56242a7fd
Revises: 97a876893a1f
Create Date: 2025-08-01 15:32:45.019333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a56242a7fd'
down_revision: Union[str, None] = '97a876893a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('estado_cliente', sa.Enum('prospecto', 'cliente', 'inactivo', name='estadocliente'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'estado_cliente')
    # ### end Alembic commands ###
