"""creando relaciones para compras e inventarios

Revision ID: 8bc1ceabbebb
Revises: 91044f071158
Create Date: 2025-07-24 13:12:53.598184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc1ceabbebb'
down_revision: Union[str, None] = '91044f071158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entradas_compra', sa.Column('entrada_inventario_id', sa.Integer(), nullable=False))
    op.add_column('entradas_compra', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'entradas_compra', ['entrada_inventario_id'])
    op.create_foreign_key('fk_entradas_compra_entrada_inventario_id', 'entradas_compra', 'entradas_inventario', ['entrada_inventario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_entradas_compra_proveedor_id', 'entradas_compra', 'proveedores', ['proveedor_id'], ['id'], ondelete='RESTRICT')
    op.add_column('entradas_inventario', sa.Column('movimiento_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'entradas_inventario', ['movimiento_id'])
    op.create_foreign_key('fk_entradas_inventario_movimiento_id', 'entradas_inventario', 'movimientos_inventario', ['movimiento_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_entradas_inventario_almacen_id', 'entradas_inventario', 'almacenes', ['almacen_id'], ['id'], ondelete='RESTRICT')
    op.add_column('productos_comprados', sa.Column('entrada_compra_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_productos_comprados_entrada_compra_id', 'productos_comprados', 'entradas_compra', ['entrada_compra_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_productos_comprados_producto_id', 'productos_comprados', 'productos', ['producto_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_productos_comprados_producto_id', 'productos_comprados', type_='foreignkey')
    op.drop_constraint('fk_productos_comprados_entrada_compra_id', 'productos_comprados', type_='foreignkey')
    op.drop_column('productos_comprados', 'entrada_compra_id')
    op.drop_constraint('fk_entradas_inventario_almacen_id', 'entradas_inventario', type_='foreignkey')
    op.drop_constraint('fk_entradas_inventario_movimiento_id', 'entradas_inventario', type_='foreignkey')
    op.drop_constraint(None, 'entradas_inventario', type_='unique')
    op.drop_column('entradas_inventario', 'movimiento_id')
    op.drop_constraint('fk_entradas_compra_proveedor_id', 'entradas_compra', type_='foreignkey')
    op.drop_constraint('fk_entradas_compra_entrada_inventario_id', 'entradas_compra', type_='foreignkey')
    op.drop_constraint(None, 'entradas_compra', type_='unique')
    op.drop_column('entradas_compra', 'proveedor_id')
    op.drop_column('entradas_compra', 'entrada_inventario_id')
    # ### end Alembic commands ###
