"""Initial migration

Revision ID: 943f15d305fd
Revises: 
Create Date: 2025-01-21 14:54:32.731662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943f15d305fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('tipo_persona', sa.Enum('FISICA', 'MORAL', name='tipopersona'), nullable=False),
    sa.Column('regimen_fiscal', sa.String(length=100), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=255), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('telefonos_fijos', sa.JSON(), nullable=True),
    sa.Column('telefonos_celulares', sa.JSON(), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True),
    sa.Column('calle', sa.String(length=255), nullable=True),
    sa.Column('numero_exterior', sa.String(length=50), nullable=True),
    sa.Column('numero_interior', sa.String(length=50), nullable=True),
    sa.Column('colonia', sa.String(length=255), nullable=True),
    sa.Column('localidad', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=5), nullable=True),
    sa.Column('facturar_ventas', sa.Boolean(), nullable=False),
    sa.Column('dias_credito', sa.Integer(), nullable=True),
    sa.Column('monto_credito', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('emisores',
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('tipo_persona', sa.Enum('FISICA', 'MORAL', name='tipopersona'), nullable=False),
    sa.Column('regimen_fiscal', sa.String(length=100), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('calle', sa.String(length=255), nullable=True),
    sa.Column('numero_exterior', sa.String(length=50), nullable=True),
    sa.Column('numero_interior', sa.String(length=50), nullable=True),
    sa.Column('colonia', sa.String(length=255), nullable=True),
    sa.Column('localidad', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=5), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=20), nullable=True),
    sa.Column('numero_tarjeta', sa.String(length=16), nullable=True),
    sa.Column('clabe', sa.String(length=18), nullable=True),
    sa.Column('certificado_path', sa.String(length=255), nullable=True),
    sa.Column('clave_privada_path', sa.String(length=255), nullable=True),
    sa.Column('numero_certificado', sa.String(length=100), nullable=True),
    sa.Column('contrasena_clave', sa.String(length=255), nullable=True),
    sa.Column('es_pruebas', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc')
    )
    op.create_index(op.f('ix_emisores_id'), 'emisores', ['id'], unique=False)
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('curp', sa.String(length=18), nullable=True),
    sa.Column('gender', sa.Enum('MASCULINO', 'FEMENINO', name='sexo'), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('emergency_phone', sa.String(length=15), nullable=True),
    sa.Column('emergency_phone_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_phone_relationship', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('drivers_license', sa.String(length=50), nullable=True),
    sa.Column('contract_term', sa.Enum('DETERMINADO', 'INDETERMINADO', name='plazocontrato'), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('payment_period', sa.Enum('SEMANAL', 'QUINCENAL', 'MENSUAL', name='paymentperiod'), nullable=True),
    sa.Column('nss', sa.String(length=11), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('infonavit_credit', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('immediate_boss_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVO', 'INACTIVO', 'VACACIONES', 'INCAPACIDAD', name='status'), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('blood_type', sa.Enum('O+', 'O-', 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', name='bloodtype'), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('shoe_size', sa.Enum('22', '22.5', '23', '23.5', '24', '24.5', '25', '25.5', '26', '26.5', '27', '27.5', '28', '28.5', '29', '29.5', '30', name='tallacalzado'), nullable=True),
    sa.Column('uniform_size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', name='tallauniforme'), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], name='fk_empleado_almacen', use_alter=True),
    sa.ForeignKeyConstraint(['immediate_boss_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('encargado_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encargado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('descuento_general', sa.Float(), nullable=False),
    sa.Column('gastos_envio', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('condiciones_venta', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['emisor_id'], ['emisores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('Administrador', 'Recursos humanos', 'Empleado', 'Emisor', 'Observador', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('clave_sat', sa.String(length=50), nullable=True),
    sa.Column('concepto_sat', sa.String(length=255), nullable=True),
    sa.Column('um_sat', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('unidad_compra', sa.String(length=50), nullable=True),
    sa.Column('unidad_venta', sa.String(length=50), nullable=True),
    sa.Column('factor', sa.Float(), nullable=True),
    sa.Column('dimensiones', sa.String(length=100), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('dias_garantia', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('precio_renta', sa.Float(), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizacion_productos',
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('cotizacion_id', 'producto_id', 'id')
    )
    op.create_index(op.f('ix_cotizacion_productos_id'), 'cotizacion_productos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cotizacion_productos_id'), table_name='cotizacion_productos')
    op.drop_table('cotizacion_productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('cotizaciones')
    op.drop_table('almacenes')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_emisores_id'), table_name='emisores')
    op.drop_table('emisores')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
