"""agregando soft delete a provedoores y estado compras

Revision ID: 97a876893a1f
Revises: f650b0a4f58e
Create Date: 2025-07-31 17:25:32.664982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a876893a1f'
down_revision: Union[str, None] = 'f650b0a4f58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedores', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedores', 'active')
    # ### end Alembic commands ###
