"""cambiando columna phone_number en empleado de int a string

Revision ID: ae1496fd9c79
Revises: fcacf44dd658
Create Date: 2025-01-28 20:58:42.494420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae1496fd9c79'
down_revision: Union[str, None] = 'fcacf44dd658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sucursales', 'phone_number',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sucursales', 'phone_number',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
