"""regimen fiscal y tipo persona en clientes pasan a enums tomando en cuenta los valores para almacenar en la base de datos

Revision ID: bf3a36d3b55a
Revises: 518ded7fbf43
Create Date: 2025-02-08 17:33:03.189769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf3a36d3b55a'
down_revision: Union[str, None] = '518ded7fbf43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'tipo_persona',
               existing_type=mysql.ENUM('FISICA', 'MORAL'),
               nullable=True)
    op.alter_column('clientes', 'regimen_fiscal',
               existing_type=mysql.ENUM('NOSE'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'regimen_fiscal',
               existing_type=mysql.ENUM('NOSE'),
               nullable=False)
    op.alter_column('clientes', 'tipo_persona',
               existing_type=mysql.ENUM('FISICA', 'MORAL'),
               nullable=False)
    # ### end Alembic commands ###
