"""add concepto y precio unitario a producto cotizado a tabla productos_cotizados

Revision ID: c281846f9785
Revises: 3296a3a07065
Create Date: 2025-03-03 18:06:12.300222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c281846f9785'
down_revision: Union[str, None] = '3296a3a07065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos_cotizados', sa.Column('concepto', sa.String(length=255), nullable=False))
    op.add_column('productos_cotizados', sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos_cotizados', 'precio_unitario')
    op.drop_column('productos_cotizados', 'concepto')
    # ### end Alembic commands ###
