"""corrigiendo relaciones final

Revision ID: ca39ffd9dfdb
Revises: 251b34ec5de5
Create Date: 2025-01-28 02:20:13.007932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca39ffd9dfdb'
down_revision: Union[str, None] = '251b34ec5de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'areas', 'empresas', ['empresa_id'], ['id'])
    op.drop_column('areas', 'empleado_id')
    op.create_foreign_key(None, 'categorias_productos', 'departamentos_productos', ['departamento_id'], ['id'])
    op.create_foreign_key(None, 'clientes', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'cotizaciones', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'cotizaciones', 'logos', ['logo_id'], ['id'])
    op.create_foreign_key(None, 'cotizaciones', 'emisores', ['emisor_id'], ['id'])
    op.create_foreign_key(None, 'departamentos_productos', 'empresas', ['empresa_id'], ['id'])
    op.add_column('emisores', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.drop_index('ix_emisores_id', table_name='emisores')
    op.create_foreign_key(None, 'emisores', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'inventario', 'productos', ['producto_id'], ['id'])
    op.create_foreign_key(None, 'inventario', 'almacenes', ['almacen_id'], ['id'])
    op.add_column('logos', sa.Column('name', sa.String(length=30), nullable=False))
    op.create_foreign_key(None, 'logos', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'productos', 'subcategorias_productos', ['subcategoria_id'], ['id'])
    op.create_foreign_key(None, 'productos_cotizados', 'cotizaciones', ['cotizacion_id'], ['id'])
    op.create_foreign_key(None, 'productos_cotizados', 'productos', ['producto_id'], ['id'])
    op.create_foreign_key(None, 'subcategorias_productos', 'categorias_productos', ['categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategorias_productos', type_='foreignkey')
    op.drop_constraint(None, 'productos_cotizados', type_='foreignkey')
    op.drop_constraint(None, 'productos_cotizados', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'logos', type_='foreignkey')
    op.drop_column('logos', 'name')
    op.drop_constraint(None, 'inventario', type_='foreignkey')
    op.drop_constraint(None, 'inventario', type_='foreignkey')
    op.drop_constraint(None, 'emisores', type_='foreignkey')
    op.create_index('ix_emisores_id', 'emisores', ['id'], unique=False)
    op.drop_column('emisores', 'empresa_id')
    op.drop_constraint(None, 'departamentos_productos', type_='foreignkey')
    op.drop_constraint(None, 'cotizaciones', type_='foreignkey')
    op.drop_constraint(None, 'cotizaciones', type_='foreignkey')
    op.drop_constraint(None, 'cotizaciones', type_='foreignkey')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_constraint(None, 'categorias_productos', type_='foreignkey')
    op.add_column('areas', sa.Column('empleado_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'areas', type_='foreignkey')
    # ### end Alembic commands ###
