"""agregar_campos_precio_base_y_iva_a_productos_vendidos

Revision ID: dcd80891a1f1
Revises: e2e9c2d71912
Create Date: 2025-08-21 09:57:02.816717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd80891a1f1'
down_revision: Union[str, None] = 'e2e9c2d71912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos_vendidos', sa.Column('precio_unitario_original', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('productos_vendidos', sa.Column('incluye_iva_original', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos_vendidos', 'incluye_iva_original')
    op.drop_column('productos_vendidos', 'precio_unitario_original')
    # ### end Alembic commands ###
