"""add salidas inventario models

Revision ID: e2e9c2d71912
Revises: 85a56242a7fd
Create Date: 2025-08-18 12:35:35.679016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e9c2d71912'
down_revision: Union[str, None] = '85a56242a7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salidas_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_salida', sa.Enum('VENTA', 'AJUSTE_NEGATIVO', 'TRANSFERENCIA_ENVIADA', name='tiposalida'), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('numero_documento', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_inventario.id'], name='fk_salidas_inventario_movimiento_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_id')
    )
    op.create_table('salidas_venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salida_inventario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cotizacion_id', sa.Integer(), nullable=True),
    sa.Column('numero_factura', sa.String(length=100), nullable=True),
    sa.Column('fecha_factura', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'TARJETA_CREDITO', 'TARJETA_DEBITO', 'CREDITO', name='metodopago'), nullable=True),
    sa.Column('costo_envio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='fk_salidas_venta_cliente_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], name='fk_salidas_venta_cotizacion_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salida_inventario_id'], ['salidas_inventario.id'], name='fk_salidas_venta_salida_inventario_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salida_inventario_id')
    )
    op.create_table('productos_vendidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salida_venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], name='fk_productos_vendidos_almacen_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='fk_productos_vendidos_producto_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salida_venta_id'], ['salidas_venta.id'], name='fk_productos_vendidos_salida_venta_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('entradas_inventario_ibfk_1', 'entradas_inventario', type_='foreignkey')
    op.drop_constraint('productos_comprados_ibfk_1', 'productos_comprados', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('productos_comprados_ibfk_1', 'productos_comprados', 'productos', ['producto_id'], ['id'])
    op.create_foreign_key('entradas_inventario_ibfk_1', 'entradas_inventario', 'almacenes', ['almacen_id'], ['id'])
    op.drop_table('productos_vendidos')
    op.drop_table('salidas_venta')
    op.drop_table('salidas_inventario')
    # ### end Alembic commands ###
