"""foreign key en empleado y sucursal

Revision ID: e3457bda41f8
Revises: 6a2dc3c6c705
Create Date: 2025-01-28 11:57:03.087197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3457bda41f8'
down_revision: Union[str, None] = '6a2dc3c6c705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
