"""agregando nuevas unidades de medida en producto

Revision ID: e56a7d316c06
Revises: 453fad7be55b
Create Date: 2025-04-06 13:52:24.135485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56a7d316c06'
down_revision: Union[str, None] = '453fad7be55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('unidad_medida', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'unidad_medida')
    # ### end Alembic commands ###
