"""delete rent price from productos

Revision ID: e67d391afd6d
Revises: 30b5bb2eb86b
Create Date: 2025-04-02 18:03:28.739485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e67d391afd6d'
down_revision: Union[str, None] = '30b5bb2eb86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('unidad_medida', sa.String(length=3), nullable=False))
    op.drop_column('productos', 'rent_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('rent_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('productos', 'unidad_medida')
    # ### end Alembic commands ###
